//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolmastery.Managers.ResourceMgr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientParameterCatalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientParameterCatalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lolmastery.Managers.ResourceMgr.ClientParameterCatalog", typeof(ClientParameterCatalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {id}.
        /// </summary>
        public static string ChampionID {
            get {
                return ResourceManager.GetString("ChampionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {matchId}.
        /// </summary>
        public static string MatchID {
            get {
                return ResourceManager.GetString("MatchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {platformId}.
        /// </summary>
        public static string PlatformID {
            get {
                return ResourceManager.GetString("PlatformID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {playerId}.
        /// </summary>
        public static string PlayerID {
            get {
                return ResourceManager.GetString("PlayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {region}.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {summonerIds}.
        /// </summary>
        public static string SummonerID {
            get {
                return ResourceManager.GetString("SummonerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {summonerNames}.
        /// </summary>
        public static string SummonerName {
            get {
                return ResourceManager.GetString("SummonerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {teamIds}.
        /// </summary>
        public static string TeamID {
            get {
                return ResourceManager.GetString("TeamID", resourceCulture);
            }
        }
    }
}
