//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolmastery.Managers.ResourceMgr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RiotApiCatalog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RiotApiCatalog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lolmastery.Managers.ResourceMgr.RiotApiCatalog", typeof(RiotApiCatalog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/lol/static-data/{region}/v1.2/champion/{id}.
        /// </summary>
        public static string CH_GET_CHAMPION_INFO {
            get {
                return ResourceManager.GetString("CH_GET_CHAMPION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/lol/static-data/{region}/v1.2/champion.
        /// </summary>
        public static string CH_GET_CHAMPIONCATALOG {
            get {
                return ResourceManager.GetString("CH_GET_CHAMPIONCATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /championmastery/location/{platformId}/player/{playerId}/champions.
        /// </summary>
        public static string CH_GET_CHAMPIONMASTERY_BY_PLATFORM_AND_PLAYERID {
            get {
                return ResourceManager.GetString("CH_GET_CHAMPIONMASTERY_BY_PLATFORM_AND_PLAYERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /championmastery/location/{platformId}/player/{playerId}/score.
        /// </summary>
        public static string CH_GET_CHAMPIONMASTERY_SCORE {
            get {
                return ResourceManager.GetString("CH_GET_CHAMPIONMASTERY_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/lol/{region}/v2.5/league/by-summoner/{summonerIds}/entry.
        /// </summary>
        public static string LG_GET_SUMMONERLEAGUEBYSUMMONERNAME {
            get {
                return ResourceManager.GetString("LG_GET_SUMMONERLEAGUEBYSUMMONERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/lol/{region}/v2.5/league/challenger.
        /// </summary>
        public static string MS_GET_CHALLENGER {
            get {
                return ResourceManager.GetString("MS_GET_CHALLENGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/lol/{region}/v2.5/league/master.
        /// </summary>
        public static string MS_GET_MASTER {
            get {
                return ResourceManager.GetString("MS_GET_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/lol/{region}/v1.4/summoner/{summonerIds}/runes.
        /// </summary>
        public static string SM_GET_RUNES_BY_SUMMONERID {
            get {
                return ResourceManager.GetString("SM_GET_RUNES_BY_SUMMONERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/lol/{region}/v1.4/summoner/{summonerIds}/masteries.
        /// </summary>
        public static string SM_GET_SUMMONER_MASTERIES_BY_SUMMONERID {
            get {
                return ResourceManager.GetString("SM_GET_SUMMONER_MASTERIES_BY_SUMMONERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/lol/{region}/v1.4/summoner/by-name/{summonerNames}.
        /// </summary>
        public static string SM_GET_SUMMONERINFO_BY_NAME {
            get {
                return ResourceManager.GetString("SM_GET_SUMMONERINFO_BY_NAME", resourceCulture);
            }
        }
    }
}
